apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: documentation
  description: This website is to centralise the documentation of the project.
  tags:
    - markdown
  annotations:
    github.com/project-slug: POC-CONSENSUS/documentation
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: group:poc-consensus/awesometeam
  system: naming-convention-generator
